/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.webclient;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        WebClientDemo webClientDemo = new WebClientDemo();
        webClientDemo.demo();
    }
}
